server:
  ssl:
    enabled: false

spring:
  datasource:
    username: favorite_recipes
    url: jdbc:h2:mem:recipes;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS FAVORITE_RECIPES
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false # set to true for debugging integration tests
        format_sql: false # set to true for debugging integration tests
        ddl-auto: update
        search:
          automatic_indexing:
            synchronization:
              strategy:
          backend:
            type: lucene
            directory.root: ./data/index

springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    enabled: true